### ISSUE TITLE
add autolinking to github repo

### ISSUE THREAD

**Issue by davidkarlsen** [openshift/cluster-logging-operator#1047]
can you add [autolinks](https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/configuring-autolinks-to-reference-external-resources) to this github repo, so that jumping over to correct issues in https://issues.redhat.com/browse/LOG and https://issues.redhat.com/browse/RHDEVDOCS becomes a breeze? thanks.

**Comment by jcantrill** [comment]
We are unable to accommodate your request due to the organizational plan.
