### ISSUE TITLE
The gather_elasticsearch_operator_resources script does not capture elasticsearch operator logs

### ISSUE THREAD

**Issue by jnordell** [openshift/cluster-logging-operator#1329]
**Describe the bug**
The /bin/gather_elasticsearch_operator_resources script does not collect elasticsearch-operator logs

**Environment**
- Image registry.redhat.io/openshift-logging/cluster-logging-rhel8-operator@sha256:4355370442a1e722ec3fd7679b362d5f04f32016029ea2d243142a0e6ee551e0

**Logs**
$ cat elasticsearch-operator.logs
error: a container name must be specified for pod elasticsearch-operator-68fff7dc7-gwq4l, choose one of: [kube-rbac-proxy elasticsearch-operator]

**Expected behavior**
 elasticsearch-operator.logs should contain the log

**Actual behavior**
 elasticsearch-operator.logs contain only the error message 

**To Reproduce**
1. oc adm must-gather --image=$(oc -n openshift-logging get deployment.apps/cluster-logging-operator -o jsonpath='{.spec.template.spec.containers[?(@.name == "cluster-logging-operator")].image}')
2. Check content of the file "cluster-logging/eo/elasticsearch-operator.logs"
3. 

**Additional context**
Specifying the container in the command should solve the issue

**Comment by jcantrill** [comment]
fixed by https://github.com/openshift/cluster-logging-operator/pull/1330
