### ISSUE TITLE
Error following automatic update to cluster-logging-operator 5.5

### ISSUE THREAD

**Issue by llomgui** [openshift/cluster-logging-operator#1785]
**Describe the bug**
I had an automatic update of cluster-logging-operator from 5.4 to 5.5.

**Environment**
- OKD 4.11
- cluster-logging-operator 5.5

**Logs**
{"_ts":"2022-12-09T10:49:15.165800454Z","_level":"0","_component":"cluster-logging-operator","_message":"Manager exited non-zero","_error":{"msg":"failed to wait for clusterlogging caches to sync: timed out waiting for cache to be synced"}}
![image](https://user-images.githubusercontent.com/14892748/206686057-4d25426e-4a37-48cd-99e6-9826d3eaa8c1.png)

**Expected behavior**
Have a smooth upgrade between 5.4 and 5.5

**Actual behavior**
Operator is broken

**Comment by toastbrotch** [comment]
same here

**Comment by jcantrill** [comment]
https://issues.redhat.com/browse/LOG-3407
