### ISSUE TITLE
Change repository permissions

### ISSUE THREAD

**Issue by josefkarasek** [openshift/cluster-logging-operator#18]
I had a badly set up .git/config and by mistake pushed into upstream / master.

Can we change repo settings so that direct pushes are always declined?

**Comment by jcantrill** [comment]
@smarterclayton who can set that config?

**Comment by josefkarasek** [comment]
We want
* `restrict-master-to-gui-merges.sh`
* `block_self_merge_prs.sh`
from https://github.com/github/platform-samples/tree/master/pre-receive-hooks

**Comment by jcantrill** [comment]
@stevekuznetsov is this something we need to be concerned with or address?

**Comment by stevekuznetsov** [comment]
Sure -- @openshift/openshift-team-developer-productivity-platform should be able to set this on the repo using their automation. You may want to make a ticket on their JIRA.

**Comment by coverprice** [comment]
Github's branch protection feature allows us to restrict who can push to a branch, but be aware that repo admins and maintainers always have push permissions.
