### ISSUE TITLE
Add `system:serviceaccount:openshift-logging:fluentd` to privileged scc

### ISSUE THREAD

**Issue by josefkarasek** [openshift/cluster-logging-operator#19]
Fluentd needs to run as privileged container

https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_logging_fluentd/tasks/main.yaml#L72-L79

**Comment by josefkarasek** [comment]
Can we document all prerequisites that need to be done before the operator can start?

**Comment by ewolinetz** [comment]
This should already be on the list of prereqs that the privileged operator will have to do for us.
The step for this is a part of this [1] pr.

[1] https://github.com/openshift/cluster-logging-operator/pull/16/files#diff-04c6e90faac2675aa89e2176d2eec7d8R24

**Comment by josefkarasek** [comment]
@ewolinetz also
```
echo 'vm.max_map_count=262144' | sudo tee --append /etc/sysctl.d/99-elasticsearch.conf
sudo sysctl -p /etc/sysctl.d/99-elasticsearch.conf
```
