### ISSUE TITLE
ClusterLogForwarder input validation error for clusterlogging crd

### ISSUE THREAD

**Issue by seilorjunior** [openshift/cluster-logging-operator#1946]
**Describe the bug**
I am following the steps from  https://docs.openshift.com/container-platform/4.10/logging/cluster-logging-deploying.html.

On the step 3 (Create an OpenShift Logging instance) i have used the same manifest, but i am getting this error ClusterLogForwarder input validation error

**Environment**
- Versions of OpenShift, Cluster Logging  and any other relevant components
- ClusterLogging instance

**Logs**
{"_ts":"2023-04-03T13:15:04.17984957Z","_level":"0","_component":"cluster-logging-operator","_message":"starting up...","go_arch":"amd64","go_os":"linux","go_version":"go1.18.9","operator_version":"5.6"}
I0403 13:15:05.230640       1 request.go:682] Waited for 1.038713295s due to client-side throttling, not priority and fairness, request: GET:https://172.30.0.1:443/apis/network.openshift.io/v1?timeout=32s
{"_ts":"2023-04-03T13:15:07.350466214Z","_level":"0","_component":"cluster-logging-operator","_message":"migrating resources provided by the manifest"}
{"_ts":"2023-04-03T13:15:07.355669986Z","_level":"0","_component":"cluster-logging-operator","_message":"Registering Components."}
{"_ts":"2023-04-03T13:15:07.356058092Z","_level":"0","_component":"cluster-logging-operator","_message":"Starting the Cmd."}
{"_ts":"2023-04-03T13:21:51.965654845Z","_level":"0","_component":"cluster-logging-operator","_message":"Unable to generate log configuration","_error":{"msg":"No valid inputs found in ClusterLogForwarder"}}
{"_ts":"2023-04-03T13:21:52.004871392Z","_level":"0","_component":"cluster-logging-operator","_message":"clusterRequest.generateCollectorConfig","_error":{"msg":"No valid inputs found in ClusterLogForwarder"}}
{"_ts":"2023-04-03T13:21:52.004993994Z","_level":"0","_component":"cluster-logging-operator","_message":"Error reconciling clusterlogging instance","_error":{"msg":"unable to create or update collection for \"instance\": No valid inputs found in ClusterLogForwarder"}}
{"_ts":"2023-04-03T13:21:52.038047839Z","_level":"0","_component":"cluster-logging-operator","_message":"clusterlogging-controller error updating status","_error":{"msg":"Operation cannot be fulfilled on clusterloggings.logging.openshift.io \"instance\": the object has been modified; please apply your changes to the latest version and try again"}}
{"_ts":"2023-04-03T13:21:52.129108141Z","_level":"0","_component":"cluster-logging-operator","_message":"Unable to generate log configuration","_error":{"msg":"No valid inputs found in ClusterLogForwarder"}}
{"_ts":"2023-04-03T13:21:52.129211643Z","_level":"0","_component":"cluster-logging-operator","_message":"clusterRequest.generateCollectorConfig","_error":{"msg":"No valid inputs found in ClusterLogForwarder"}}
{"_ts":"2023-04-03T13:21:52.129260344Z","_level":"0","_component":"cluster-logging-operator","_message":"Error reconciling clusterlogging instance","_error":{"msg":"unable to create or update collection for \"instance\": No valid inputs found in ClusterLogForwarder"}}
{"_ts":"2023-04-03T13:21:52.213587335Z","_level":"0","_component":"cluster-logging-operator","_message":"Unable to generate log configuration","_error":{"msg":"No valid inputs found in ClusterLogForwarder"}}
{"_ts":"2023-04-03T13:21:52.213837239Z","_level":"0","_component":"cluster-logging-operator","_message":"clusterRequest.generateCollectorConfig","_error":{"msg":"No valid inputs found in ClusterLogForwarder"}}
{"_ts":"2023-04-03T13:21:52.214912457Z","_level":"0","_component":"cluster-logging-operator","_message":"Error reconciling clusterlogging instance","_error":{"msg":"unable to create or update collection for \"instance\": No valid inputs found in ClusterLogForwarder"}}
{"_ts":"2023-04-03T13:21:52.301252781Z","_level":"0","_component":"cluster-logging-operator","_message":"Unable to generate log configuration","_error":{"msg":"No valid inputs found in ClusterLogForwarder"}}
{"_ts":"2023-04-03T13:21:52.301348082Z","_level":"0","_component":"cluster-logging-operator","_message":"clusterRequest.generateCollectorConfig","_error":{"msg":"No valid inputs found in ClusterLogForwarder"}}
{"_ts":"2023-04-03T13:21:52.301399683Z","_level":"0","_component":"cluster-logging-operator","_message":"Error reconciling clusterlogging instance","_error":{"msg":"unable to create or update collection for \"instance\": No valid inputs found in ClusterLogForwarder"}}
{"_ts":"2023-04-03T13:21:52.395486535Z","_level":"0","_component":"cluster-logging-operator","_message":"Unable to generate log configuration","_error":{"msg":"No valid inputs found in ClusterLogForwarder"}}
{"_ts":"2023-04-03T13:21:52.395582737Z","_level":"0","_component":"cluster-logging-operator","_message":"clusterRequest.generateCollectorConfig","_error":{"msg":"No valid inputs found in ClusterLogForwarder"}}
{"_ts":"2023-04-03T13:21:52.395628737Z","_level":"0","_component":"cluster-logging-operator","_message":"Error reconciling clusterlogging instance","_error":{"msg":"unable to create or update collection for \"instance\": No valid inputs found in ClusterLogForwarder"}}
{"_ts":"2023-04-03T13:21:52.467866429Z","_level":"0","_component":"cluster-logging-operator","_message":"Unable to generate log configuration","_error":{"msg":"No valid inputs found in ClusterLogForwarder"}}
{"_ts":"2023-04-03T13:21:52.46795463Z","_level":"0","_component":"cluster-logging-operator","_message":"clusterRequest.generateCollectorConfig","_error":{"msg":"No valid inputs found in ClusterLogForwarder"}}
{"_ts":"2023-04-03T13:21:52.468003731Z","_level":"0","_component":"cluster-logging-operator","_message":"Error reconciling clusterlogging instance","_error":{"msg":"unable to create or update collection for \"instance\": No valid inputs found in ClusterLogForwarder"}}
{"_ts":"2023-04-03T13:21:52.562123283Z","_level":"0","_component":"cluster-logging-operator","_message":"Unable to generate log configuration","_error":{"msg":"No valid inputs found in ClusterLogForwarder"}}
{"_ts":"2023-04-03T13:21:52.562220785Z","_level":"0","_component":"cluster-logging-operator","_message":"clusterRequest.generateCollectorConfig","_error":{"msg":"No valid inputs found in ClusterLogForwarder"}}
{"_ts":"2023-04-03T13:21:52.562264486Z","_level":"0","_component":"cluster-logging-operator","_message":"Error reconciling clusterlogging instance","_error":{"msg":"unable to create or update collection for \"instance\": No valid inputs found in ClusterLogForwarder"}}
{"_ts":"2023-04-03T13:21:52.967459669Z","_level":"0","_component":"cluster-logging-operator","_message":"Unable to generate log configuration","_error":{"msg":"No valid inputs found in ClusterLogForwarder"}}
{"_ts":"2023-04-03T13:21:52.967554471Z","_level":"0","_component":"cluster-logging-operator","_message":"clusterRequest.generateCollectorConfig","_error":{"msg":"No valid inputs found in ClusterLogForwarder"}}
{"_ts":"2023-04-03T13:21:52.967601571Z","_level":"0","_component":"cluster-logging-operator","_message":"Error reconciling clusterlogging instance","_error":{"msg":"unable to create or update collection for \"instance\": No valid inputs found in ClusterLogForwarder"}}
{"_ts":"2023-04-03T13:21:53.706615761Z","_level":"0","_component":"cluster-logging-operator","_message":"Unable to generate log configuration","_error":{"msg":"No valid inputs found in ClusterLogForwarder"}}
{"_ts":"2023-04-03T13:21:53.706753263Z","_level":"0","_component":"cluster-logging-operator","_message":"clusterRequest.generateCollectorConfig","_error":{"msg":"No valid inputs found in ClusterLogForwarder"}}
{"_ts":"2023-04-03T13:21:53.706799964Z","_level":"0","_component":"cluster-logging-operator","_message":"Error reconciling clusterlogging instance","_error":{"msg":"unable to create or update collection for \"instance\": No valid inputs found in ClusterLogForwarder"}}
{"_ts":"2023-04-03T13:21:55.067977415Z","_level":"0","_component":"cluster-logging-operator","_message":"Unable to generate log configuration","_error":{"msg":"No valid inputs found in ClusterLogForwarder"}}

**Comment by jcantrill** [comment]
where are the sample clusterlogging and clusterlogforwarder (if appropriate) instances?

**Comment by seilorjunior** [comment]
@jcantrill hey, the documentation only shows the clusterlogging.
The version of the operator is 
![image](https://user-images.githubusercontent.com/13451867/229569911-b5d927a1-d47e-4308-ae8a-29bb1bdb537d.png)

**Comment by seilorjunior** [comment]
> where are the sample clusterlogging and clusterlogforwarder (if appropriate) instances?

The example is from the documentation
`apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  name: "instance" 
  namespace: "openshift-logging"
spec:
  managementState: "Managed"  
  logStore:
    type: "elasticsearch"  
    retentionPolicy: 
      application:
        maxAge: 1d
      infra:
        maxAge: 7d
      audit:
        maxAge: 7d
    elasticsearch:
      nodeCount: 3 
      storage:
        storageClassName: "<storage-class-name>" 
        size: 200G
      resources: 
        limits:
          memory: "16Gi"
        requests:
          memory: "16Gi"
      proxy: 
        resources:
          limits:
            memory: 256Mi
          requests:
             memory: 256Mi
      redundancyPolicy: "SingleRedundancy"
  visualization:
    type: "kibana"  
    kibana:
      replicas: 1
  collection:
    logs:
      type: "fluentd"  
      fluentd: {}`

**Comment by MastanaGuru** [comment]
Hi @seilorjunior, With Redhat logging operator 5.5.x the clusterlogging crd has changed. spec.collection**.log.** has been deprecated and in 5.6.4 version of the crd, it has been removed.
Instead of
~~~
  collection:
    logs:
      type: "fluentd"  
      fluentd: {}
~~~
 
can you test with  
~~~
  collection:
    type: "fluentd"  
    fluentd: {}
~~~
