### ISSUE TITLE
Delete LOG-411 branch

### ISSUE THREAD

**Issue by lukas-vlcek** [openshift/cluster-logging-operator#195]
I created branch [LOG-411](https://github.com/openshift/cluster-logging-operator/tree/LOG-411) by an accident. I do not think I have privs to delete it. Please remove this branch.

**Comment by lukas-vlcek** [comment]
Ping, @jcantrill @ewolinetz

**Comment by jcantrill** [comment]
I dont have permissions to do this.  @stevekuznetsov ?

**Comment by stevekuznetsov** [comment]
Done!
/close
