### ISSUE TITLE
Bundle unpacking failed. Reason: DeadlineExceeded, and Message: Job was active longer than specified deadline

### ISSUE THREAD

**Issue by 666MrFang** [openshift/cluster-logging-operator#1966]
When I use web control to install cluster-logging,an error is reported“Bundle unpacking failed. Reason: DeadlineExceeded, and Message: Job was active longer than specified deadline”. Why?

**Comment by jcantrill** [comment]
This is an OLM question since logging produces a bundle that describes what to deploy and which images to use.  It may be related to you not having access to required images, resources.  It is really difficult to know without a more holistic view of the cluster

**Comment by MastanaGuru** [comment]
@666MrFang please refer to this KB article https://access.redhat.com/solutions/6459071

**Comment by 666MrFang** [comment]
I know the problem, because I'm an offline openshift system and need to synchronize the mirror myself. After the mirror is synchronized, the installation is successful.
