### ISSUE TITLE
Support for namespace label selectors

### ISSUE THREAD

**Issue by mpreu** [openshift/cluster-logging-operator#2500]
Hi,

at the moment, the `ClusterLogForwarder` API can only handle log selection by static namespaces or pod labels. It would be nice if label selectors can be supported for namespaces as well. This would enable much easier log selection when multiple namespaces do not share a common `glob` expression.

**Comment by jcantrill** [comment]
Does kubernetes support listing pods by namespace labels?  I've never tried. If not then it makes it much more difficult to support this request.

**Comment by jcantrill** [comment]
> I assume from the question, the current code just lets vector find the correct targets without much pre-processing?

Currently vector essentially is capable of doing the equivalent of `oc get -l` which becomes the list of pods from which it reads logs.  We couple this with a file glob to further filter out by namespace based on what is spec'd;  those files simply are not read.  This is the most efficient.  

Looking at the available config, it may be possible to accomplish this using this [setting](https://vector.dev/docs/reference/configuration/sources/kubernetes_logs/#extra_namespace_label_selector).  This will require investigation.

Consider trying it yourself by:
* setting the ClusterLogging.spec.managementState to "Unmanaged'
* Extracting the config secret
* Adding the field to the toml
* Updating the secret
* restarting the pods with 'oc delete -lcomponent=collector'
