### ISSUE TITLE
LogForwarder daemonset

### ISSUE THREAD

**Issue by Baboulinet-33** [openshift/cluster-logging-operator#2557]
Hello,

Is there a possibility to define toleration for the logforwarder ?

The daemonset is not selecting some node due to the fact I've tainted the nodes.

**Comment by jcantrill** [comment]
https://github.com/openshift/cluster-logging-operator/blob/release-5.9/api/logging/v1/clusterlogging_types.go#L349

**Comment by Baboulinet-33** [comment]
Thanks, but that's for the collector, not the forwarder

**Comment by jcantrill** [comment]
There is no separation of concern in the implementation.  The collector is the forwarder
