### ISSUE TITLE
Cluster logging install status is `Unknown`  and no resource created

### ISSUE THREAD

**Issue by lcnsir** [openshift/cluster-logging-operator#257]
refer to https://docs.openshift.com/container-platform/4.1/logging/efk-logging-deploying.html

I try to install cluster logging on my OCP 4.1.9 cluster on AWS

but after folllowing the steps, I encounter a issue that the Operator status is unkonw, and no operator is created

<img width="1388" alt="截屏2019-10-21下午2 01 51" src="https://user-images.githubusercontent.com/2377199/67180182-68b4ae80-f40b-11e9-8f78-a244ccc8eb91.png">
<img width="1301" alt="截屏2019-10-21下午2 02 44" src="https://user-images.githubusercontent.com/2377199/67180207-79652480-f40b-11e9-84fe-73354e94e237.png">

and also the elasticsearch operator

<img width="1392" alt="截屏2019-10-21下午2 03 15" src="https://user-images.githubusercontent.com/2377199/67180237-926dd580-f40b-11e9-8187-710c077032f9.png">

**Comment by lcnsir** [comment]
Is anyone can help me about what's happend

**Comment by QiaolingTang** [comment]
@lcnsir It seems that you are trying to deploy logging 4.2 to a 4.1 ocp cluster since the `channel` is `4.2` in your subscriptions. For logging 4.1, the channel name should be `preview`.

**Comment by lcnsir** [comment]
@QiaolingTang yeah, but when I run 
```
oc get packagemanifest elasticsearch-operator -n openshift-marketplace -o jsonpath='{.status.channels[].name}'
4.2
```

it's show 4.2

**Comment by lcnsir** [comment]
@QiaolingTang how could I chang the `channel ` to preview ?

**Comment by lcnsir** [comment]
When I changed the channel to `preview` it's show
![截屏2019-10-21下午2 38 00](https://user-images.githubusercontent.com/2377199/67181899-76206780-f410-11e9-8a1a-b2d5ca168627.png)

**Comment by QiaolingTang** [comment]
Is there an install plan in the `openshift-operators-redhat` namespace ? If yes, is there a csv named `elasticsearch-operator.4.1.x-2019xxxxxx` in the `openshift-operators-redhat` namespace ? Could you please execute commands `oc describe sub elasticsearch-wlwtv -n openshift-operators-redhat` , `oc describe ip $install-plan-name -n openshift-operators-redhat` and `oc describe csv elasticsearch-operator.4.1.x-2019xxxxxx -n openshift-operators-redhat ` to see if there have some error messages.
Please also run `oc get pod -n openshift-marketplace` to see if there has a pod named `elasticsearch-xxxxxxx-xxxx` and please run command `oc get catsrc -n openshift-operators-redhat` to see if the catalog source `elasticsearch` is created or not.

**Comment by lcnsir** [comment]
There is no install-plan in the openshift-operators-redhat, just one plan in all ns


```
[ec2-user@intense-katydid-install logging]$ oc describe sub elasticsearch-lkj8c -n openshift-operators-redhat
Name:         elasticsearch-lkj8c
Namespace:    openshift-operators-redhat
Labels:       <none>
Annotations:  <none>
API Version:  operators.coreos.com/v1alpha1
Kind:         Subscription
Metadata:
  Creation Timestamp:  2019-10-21T06:36:59Z
  Generate Name:       elasticsearch-
  Generation:          1
  Resource Version:    92352
  Self Link:           /apis/operators.coreos.com/v1alpha1/namespaces/openshift-operators-redhat/subscriptions/elasticsearch-lkj8c
  UID:                 2f4dab88-f3cd-11e9-861b-021259c7796c
Spec:
  Channel:                preview
  Install Plan Approval:  Automatic
  Name:                   elasticsearch-operator
  Source:                 elasticsearch
  Source Namespace:       openshift-operators-redhat
Events:                   <none>
```
```
[ec2-user@intense-katydid-install logging]$ oc get pod -n openshift-marketplace
NAME                                   READY   STATUS             RESTARTS   AGE
certified-operators-6f4b6f95c7-tjl9f   0/1     CrashLoopBackOff   46         3h38m
community-operators-65f7df975f-627sx   1/1     Running            0          3h38m
marketplace-operator-f7bbc45f6-rhzkh   1/1     Running            0          3h39m
redhat-operators-5bc9554d58-vwzzd      1/1     Running            0          3h38m
[ec2-user@intense-katydid-install logging]$ oc get catsrc -n openshift-operators-redhat
No resources found.
[ec2-user@intense-katydid-install logging]$
```

**Comment by lcnsir** [comment]
and one error from crashed  pod `certified-operators-6f4b6f95c7-tjl9f`
```
time="2019-10-21T06:57:24Z" level=fatal msg="error loading manifest from remote registry - appsody-operator.v0.2.0 specifies replacement that couldn't be found" port=50051 type=appregistry
```

**Comment by QiaolingTang** [comment]
Have you created `catalogsourceconfig` in the `openshift-marketplace` namespace ? Please check this by executing command `oc get csc -n openshift-marketplace`. It looks like the catalog source config is not created.

**Comment by lcnsir** [comment]
@QiaolingTang  
```
[ec2-user@intense-katydid-install logging]$ oc get csc -n openshift-marketplace
NAME                                                                                                                                                                                                                                          STATUS        MESSAGE                                       AGE
certified-operators                                                                                                                                                                                                                           Succeeded     The object has been successfully reconciled   3h53m
community-operators                                                                                                                                                                                                                           Succeeded     The object has been successfully reconciled   3h53m
elasticsearch                                                                                                                                                                                                                                 Configuring   Internal error occurred: admission webhook "trust.hooks.securityenforcement.admission.cloud.ibm.com" denied the request:
Deny "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:6961bcb2dd0e0240638251a2a6a5b6e39da39eea9081935b738613282645da13", no matching repositories in ClusterImagePolicy and no ImagePolicies in the "openshift-marketplace" namespace   113m
redhat-operators                                                                                                                                                                                                                              Succeeded   The object has been successfully reconciled   3h53m
```

**Comment by QiaolingTang** [comment]
The csc elasticsearch is not in a good status: `Internal error occurred: admission webhook "trust.hooks.securityenforcement.admission.cloud.ibm.com" denied the request:
Deny "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:6961bcb2dd0e0240638251a2a6a5b6e39da39eea9081935b738613282645da13", no matching repositories in ClusterImagePolicy and no ImagePolicies in the "openshift-marketplace"`, I think this is the problem why the elasticsearch-operator is not deployed successfully. 
Sorry, I don't know how to solve the problem here.

**Comment by lcnsir** [comment]
After I fixed the ClusterImagePolicy

all csc successfully
```
[ec2-user@intense-katydid-install logging]$ oc get csc -n openshift-marketplace
NAME                  STATUS      MESSAGE                                       AGE
certified-operators   Succeeded   The object has been successfully reconciled   4h1m
community-operators   Succeeded   The object has been successfully reconciled   4h1m
elasticsearch         Succeeded   The object has been successfully reconciled   122m
redhat-operators      Succeeded   The object has been successfully reconciled   4h1m

**Comment by lcnsir** [comment]
now the status is good now
<img width="1353" alt="截屏2019-10-21下午3 17 22" src="https://user-images.githubusercontent.com/2377199/67184254-ef6e8900-f415-11e9-85da-4eb11245c99b.png">
