### ISSUE TITLE
500 Internal Error Additional Trusted CA Bundle missing

### ISSUE THREAD

**Issue by gfvirga** [openshift/cluster-logging-operator#261]
Hello,

Internally signed TLS CAtrusted bundled are not being copied to the kibana and kibana-proxy pod.

I had to set the Operator to unmanaged and created the configmap with the additional trusted CA bundle - named: "trusted-ca-bundle"

Then modified the deployment.

```
$ diff -U5 deployment_kibana.yaml.old deployment_kibana.yaml
--- deployment_kibana.yaml.old  2019-10-25 09:01:02.446738600 -0400
+++ deployment_kibana.yaml      2019-10-25 09:00:10.815299500 -0400
@@ -87,10 +87,13 @@
         terminationMessagePolicy: File
         volumeMounts:
         - mountPath: /etc/kibana/keys
           name: kibana
           readOnly: true
+        - mountPath: /etc/pki/ca-trust/extracted/pem
+          name: trusted-ca-bundle
+          readOnly: true
       - args:
         - --upstream-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
         - --https-address=:3000
         - -provider=openshift
         - -client-id=system:serviceaccount:openshift-logging:kibana
@@ -128,10 +131,13 @@
         terminationMessagePolicy: File
         volumeMounts:
         - mountPath: /secret
           name: kibana-proxy
           readOnly: true
+        - mountPath: /etc/pki/ca-trust/extracted/pem
+          name: trusted-ca-bundle
+          readOnly: true
       dnsPolicy: ClusterFirst
       nodeSelector:
         kubernetes.io/os: linux
         node-role.kubernetes.io/infra: ""
       restartPolicy: Always
@@ -147,10 +153,17 @@
           secretName: kibana
       - name: kibana-proxy
         secret:
           defaultMode: 420
           secretName: kibana-proxy
+      - configMap:
+          defaultMode: 420
+          items:
+          - key: ca-bundle.crt
+            path: tls-ca-bundle.pem
+          name: trusted-ca-bundle
+        name: trusted-ca-bundle
 status:
   availableReplicas: 1
   conditions:
   - lastTransitionTime: "2019-10-24T18:21:02Z"
     lastUpdateTime: "2019-10-24T18:21:02Z"
```

**Comment by jcantrill** [comment]
> Hello,
> 
> Internally signed TLS CAtrusted bundled are not being copied to the kibana and kibana-proxy pod.
> 
Copied from where?

**Comment by gfvirga** [comment]
It's not being copied from the installation variable additionalTrustBundle.

**Comment by gfvirga** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1766187

**Comment by wking** [comment]
> Can you point me to how we might accomplish this in 4.x?

I think it's just 4.2+ where we got the proxy config, not 4.1.  And @danehans can probably speak more authoritatively, but the general idea looks like openshift/cloud-credential-operator#111 with the fixup in openshift/cloud-credential-operator#117, where you set up a ConfigMap with a label, the label leads to the... network operator?... automatically plugging in the trust bundle, and then you mount the ConfigMap into your container.  Would be good to land some retroactive docs in openshift/enhancements around this process, if we don't have them there already.

**Comment by wking** [comment]
aha! https://github.com/openshift/enhancements/blob/b22bd620793a93edb8eb933d124b42325dfaa4d7/enhancements/proxy/global-cluster-egress-proxy.md

**Comment by wking** [comment]
And looks like there's a deployment label that lets you skip the ConfigMap.

**Comment by gfvirga** [comment]
@wking where do I have to add this config.openshift.io/inject-trusted-cabundle: "true"? Is it an annotation? Will the operator overwrite it?

**Comment by wking** [comment]
It's a label: https://github.com/openshift/enhancements/blame/b22bd620793a93edb8eb933d124b42325dfaa4d7/enhancements/proxy/global-cluster-egress-proxy.md#L154

> Will the operator overwrite it?

Set https://github.com/openshift/cluster-version-operator/blob/751c6d0c872e05f218f01d2a9f20293b4dfcca88/docs/dev/operators.md#what-if-i-only-want-the-cvo-to-create-my-resource-but-never-update-it
