### ISSUE TITLE
:warning: Action Required: Replace Deprecated gcr.io/kubebuilder/kube-rbac-proxy

### ISSUE THREAD

**Issue by camilamacedo86** [openshift/cluster-logging-operator#2884]
## Description

:warning: **The image `gcr.io/kubebuilder/kube-rbac-proxy` is deprecated and will become unavailable.**
**You must move as soon as possible, sometime from early 2025, the GCR will go away.**

> _Unfortunately, we're unable to provide any guarantees regarding timelines or potential extensions at this time. Images provided under GRC will be unavailable from March 18, 2025, [as per announcement](https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr). However, `gcr.io/kubebuilder/`may be unavailable before this date due [to efforts to deprecate infrastructure](https://github.com/kubernetes/k8s.io/issues/2647)._

- **If your project uses `gcr.io/kubebuilder/kube-rbac-proxy`, it will be affected.**
  Your project may fail to work if the image cannot be pulled. **You must take action as soon as possible.**

- However, if your project is **no longer using this image**, **no action is required**, and you can close this issue.

## Using the image `gcr.io/kubebuilder/kube-rbac-proxy`?

[kube-rbac-proxy](https://github.com/brancz/kube-rbac-proxy) was historically used to protect the metrics endpoint. However, its usage has been discontinued in [Kubebuilder](https://github.com/kubernetes-sigs/kubebuilder). The default scaffold now leverages the [`WithAuthenticationAndAuthorization`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/metrics/filters#WithAuthenticationAndAuthorization) feature provided by [Controller-Runtime](https://github.com/kubernetes-sigs/controller-runtime).

This feature provides integrated support for securing metrics endpoints by embedding authentication (`authn`) and authorization (`authz`) mechanisms directly into the controller manager's metrics server, replacing the need for (https://github.com/brancz/kube-rbac-proxy) to secure metrics endpoints.

### What To Do?

**You must replace the deprecated image `gcr.io/kubebuilder/kube-rbac-proxy` with an alternative approach. For example:**
- Update your project to use [`WithAuthenticationAndAuthorization`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/metrics/filters#WithAuthenticationAndAuthorization):
  > _You can fully upgrade your project to use the latest scaffolds provided by the tool or manually make the necessary changes. Refer to the [FAQ and Discussion](https://github.com/kubernetes-sigs/kubebuilder/discussions/3907) for detailed instructions on how to manually update your project and test the changes._
- Alternatively, replace the image with another trusted source at your own risk, as its usage has been discontinued in Kubebuilder.

**For further information, suggestions, and guidance:**
- 📖 [FAQ and Discussion](https://github.com/kubernetes-sigs/kubebuilder/discussions/3907)
- 💬 Join the Slack channel: [#kubebuilder](https://communityinviter.com/apps/kubernetes/community#kubebuilder).

> **NOTE:** _This issue was opened automatically as part of our efforts to identify projects that might be affected and to raise awareness about this change within the community. If your project is no longer using this image, **feel free to close this issue**._

We sincerely apologize for any inconvenience this may cause.

**Thank you for your cooperation and understanding!** :pray:

**Comment by xperimental** [comment]
I don't know if this issue was created automatically, but it looks like a false-positive. The only mention of that image is in `config/default/manager_auth_proxy_patch.yaml`, but that file is not pulled into the Kustomization that creates the bundle, making it effectively unused.

I also don't see us distributing that image for the final release, it might be a left-over from a previous version. I created a PR to remove the file.

**Comment by camilamacedo86** [comment]
Hi @xperimental 

> I don't know if this issue was created automatically,

I created a script to identify which projects are using it, determine what could be affected, and raise issues using the GitHub API in order to help the community. All issues raised link the issue https://github.com/kubernetes/k8s.io/issues/2647 so you can track it down.

> The only mention of that image is in config/default/manager_auth_proxy_patch.yaml, but that file is not pulled into the Kustomization that creates the bundle, making it effectively unused. 
I manually checked and it seems that you are not enabling metrics by default, as indicated in the following file:

[cluster-logging-operator/config/default/kustomization.yaml#L28-L32](https://github.com/openshift/cluster-logging-operator/blob/3f0c1695c3768979bc816f103f5b88373d7d8bc6/config/default/kustomization.yaml#L28-L32)

If you're not exposing the metrics endpoint at all and not applying that file, you won't be impacted.

That said, I would still recommend updating your source code to either remove this option entirely to avoid any potential risk or, even better, expose the metrics endpoint. Exposing metrics can be beneficial. However, also ensure that the endpoint is properly protected. You can find more information and guidance in this discussion: [Kubebuilder GitHub Discussion #3907](https://github.com/kubernetes-sigs/kubebuilder/discussions/3907).

I hope that can be helpful.

**Comment by camilamacedo86** [comment]
Hi @xperimental 

You removed the file that does the patch: https://github.com/openshift/cluster-logging-operator/pull/2886

But if you want to remove the option to export metrics, which are very important in many case scenarios, then you need to remember to remove also: https://github.com/openshift/cluster-logging-operator/blob/3f0c1695c3768979bc816f103f5b88373d7d8bc6/config/default/kustomization.yaml#L28-L32
