### ISSUE TITLE
cluster logging operator csv stuck on pending

### ISSUE THREAD

**Issue by matancarmeli7** [openshift/cluster-logging-operator#328]
Hi! I am trying to deploy the cluster logging operator with the manifests/4.2/cluster-logging.v4.2.0.clusterserviceversion.yaml file. First i creates the operatorGroups that it needs, rbac for the elasticsearch operator and deploy the elasticsearch operator also with yaml file also and in both cases the csv is stuck on pending and it writes "Service account does not exist".
When I am trying to deploy it with operatorHub its deploying successfully, but i want to deploy it on disconnected environment eventually.

Thanks

**Comment by jcantrill** [comment]
> Hi! I am trying to deploy the cluster logging operator with the manifests/4.2/cluster-logging.v4.2.0.clusterserviceversion.yaml file. First i creates the operatorGroups that it needs, rbac for the elasticsearch operator and deploy the elasticsearch operator also with yaml file also and in both cases the csv is stuck on pending and it writes "Service account does not exist".
> When I am trying to deploy it with operatorHub its deploying successfully, but i want to deploy it on disconnected environment eventually.
> 
> Thanks

The deployment of this operator is designed to work with OLM and relies on OLM deploying various dependences the operator requires (e.g. service account).  There currently is no support or intention to provide a deployment path outside of OLM

**Comment by matancarmeli7** [comment]
There is a way that i can deploy cluster logging operator in disconnected environment?

**Comment by jcantrill** [comment]
> There is a way that i can deploy cluster logging operator in disconnected environment?
> And what are those dependences that the operator requires?

Here are the disconnected docs for OCP 4.2: https://docs.openshift.com/container-platform/4.2/operators/olm-restricted-networks.htmlAnd here’s a simplified route which uses oc  to export redhat published catalogs: https://github.com/operator-framework/olm-book/blob/master/docs/snapshot-appr-registry.md

**Comment by matancarmeli7** [comment]
I know got this error: "Policy rule not satisfied for service account" when i creates the operator. I created the role, serviceaccount and role-binding and this is still writes it.
