### ISSUE TITLE
cluster logging operator pod cant use clusterlogging

### ISSUE THREAD

**Issue by matancarmeli7** [openshift/cluster-logging-operator#329]
hey, to make things clear this time - 
I have an issue deploying the operator in my environment. first I'm testing it in a **normal** cluster but at the end ill need to deploy it on a disconnected one.

I follow the instructions from those walk-throughes:
[https://github.com/operator-framework/getting-started](url)
[https://docs.openshift.com/container-platform/4.2/logging/cluster-logging-deploying.html](url)

and everything goes well until the point were i deploy the cluster logging operator csv:
[https://github.com/openshift/cluster-logging-operator/blob/release-4.2/manifests/4.2/cluster-logging.v4.2.0.clusterserviceversion.yaml](url)

where i receive the following message when i try it:
`Failed to list *v1.ClusterLogging: clusterloggings.logging.openshift.io is forbidden: User "system:serviceaccount:openshift-logging:cluster-logging-operator" cannot list resource "clusterloggings" in API group "logging.openshift.io" at the cluster scope
`

**Comment by jcantrill** [comment]
> https://github.com/openshift/cluster-logging-operator/blob/release-4.2/manifests/4.2/cluster-logging.v4.2.0.clusterserviceversion.yaml



> hey, to make things clear this time -
> I have an issue deploying the operator in my environment. first I'm testing it in a **normal** cluster but at the end ill need to deploy it on a disconnected one.
> 
> I follow the instructions from those walk-throughes:
> [https://github.com/operator-framework/getting-started](url)

You need to consider this operator and its usage as described in the ref'd url are likely not compatible.  This is not a general use operator but has been only tested to work in the context of OLM and the doc link described below. 

> [https://docs.openshift.com/container-platform/4.2/logging/cluster-logging-deploying.html](url)
> 
> and everything goes well until the point were i deploy the cluster logging operator csv:

I don't see anything in the documentation link that says "Deploy CSV from <insert url here>"

> [https://github.com/openshift/cluster-logging-operator/blob/release-4.2/manifests/4.2/cluster-logging.v4.2.0.clusterserviceversion.yaml](url)

This file is processed by our release process and likely needs additional modifications before usage; I would not expect to be able to use it in its current form

> 
> where i receive the following message when i try it:
> `Failed to list *v1.ClusterLogging: clusterloggings.logging.openshift.io is forbidden: User "system:serviceaccount:openshift-logging:cluster-logging-operator" cannot list resource "clusterloggings" in API group "logging.openshift.io" at the cluster scope `

This is a permission I would expect deploying via  OLM to resolve
