### ISSUE TITLE
Local disk volumes as in 3.X versions

### ISSUE THREAD

**Issue by camabeh** [openshift/cluster-logging-operator#352]
Hi,

I can't find any documentation about local disk volumes as in 3.X versions. (https://access.redhat.com/articles/3932191).

Is it supported?

If not, is there any alternative to it besides forwarding to different cluster or using dynamic volumes?

**Comment by jcantrill** [comment]
This operator targets 4.x clusters or better. I believe 3.x still allows for PVCs that specify a storageclass that uses local volumes.  Additionally you can consider using the older hostpath as documented https://docs.openshift.com/container-platform/3.11/install_config/aggregate_logging.html#aggregated-logging-hostPath-Elasticsearch

**Comment by camabeh** [comment]
Sorry I have written it incompletely, I need this old behavior in 4.X cluster.

**Comment by ewolinetz** [comment]
@camabeh the way to do this now would be to use a `StorageClass` backed with a local volume. StorageClassName is the only means to configure storage for Elasticsearch for 4.x
