### ISSUE TITLE
Please prepare bundle for OCP 4.5

### ISSUE THREAD

**Issue by tbielawa** [openshift/cluster-logging-operator#387]
Now that we are fully branched for 4.5, please prepare your operator to supply a 4.5 bundle, so that 4.5 operator publishing works and doesn't overwrite 4.4 bundles. This means at least updating the package.yaml under https://github.com/openshift/cluster-logging-operator/blob/master/manifests/cluster-logging.package.yaml

Reference: [Get OLM operator owners to update their CSV channels](https://issues.redhat.com/browse/ART-1559)

**Comment by jcantrill** [comment]
https://github.com/openshift/cluster-logging-operator/pull/379
