### ISSUE TITLE
Assign a priority class to pods

### ISSUE THREAD

**Issue by aveshagarwal** [openshift/cluster-logging-operator#44]
Priority classes docs:
https://docs.openshift.com/container-platform/3.11/admin_guide/scheduling/priority_preemption.html#admin-guide-priority-preemption-priority-class

Example: https://github.com/openshift/cluster-monitoring-operator/search?q=priority&unscoped_q=priority

Notes: The pre-configured system priority classes (`system-node-critical` and `system-cluster-critical`) can only be assigned to pods in `kube-system` or `openshift-*` namespaces. Most likely, core operators and their pods should be assigned `system-cluster-critical`. Please do not assign `system-node-critical` (the highest priority) unless you are really sure about it.

**Comment by ewolinetz** [comment]
We currently create a priority class of our own and assign it for our log collectors. We do not use any pre-configured system priority classes.

**Comment by jcantrill** [comment]
@smarterclayton @aveshagarwal Should we remove the priority class created by the operator in favor of the pre-configured system priority classes?  Does this better fit into consistency across the other operators?  I believe we created one specifically to address an issue in 3.11 and carried it forward.

**Comment by aveshagarwal** [comment]
Lgtm what you already have.
