### ISSUE TITLE
reconciliation resulting in certificate issue and causing elasticsearch unstable.

### ISSUE THREAD

**Issue by anuj812** [openshift/cluster-logging-operator#456]
While using Openshift 4.3.5, Cluster Logging Operator : Cluster logging Operator: 4.3.9-202003230345 , we starts getting below error after around 24 hours related to certificate and elastic search pods become down. It seems to be some bug in operator which is not able to reconcile or rotate the certificate related to elastic search and kibana ?

{"level":"error","ts":1586146160.3927138,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"logforwarding-controller","request":"openshift-logging/instance","error":"Unable to create or update certificates for "instance": Error running script: exit status 1","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/openshift/cluster-logging-operator/_output/src/github.com/go-logr/zapr/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/openshift/cluster-logging-operator/_output/src/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:217\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/openshift/cluster-logging-operator/_output/src/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/openshift/cluster-logging-operator/_output/src/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/openshift/cluster-logging-operator/_output/src/k8s.io/apimachinery/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/openshift/cluster-logging-operator/_output/src/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}

**Comment by periklis** [comment]
@anuj812 Thank you for the report. This is related to the pending fix #449.

**Comment by anuj812** [comment]
@periklis yes LogForwarding instance is enabled

**Comment by jcantrill** [comment]
Closing in favor of tracking via https://bugzilla.redhat.com/show_bug.cgi?id=1813381
