### ISSUE TITLE
Duplicate "capabilities" annotation in 4.1 CSV

### ISSUE THREAD

**Issue by thiagoalessio** [openshift/cluster-logging-operator#506]
https://github.com/openshift/cluster-logging-operator/blob/release-4.1/manifests/4.1/cluster-logging.v4.1.0.clusterserviceversion.yaml#L9,L11 has `capabilities` twice, and brew is complaining.
https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=28403199

**Comment by periklis** [comment]
@thiagoalessio Would you mind to open a BZ for this error?

**Comment by thiagoalessio** [comment]
@periklis done: https://bugzilla.redhat.com/show_bug.cgi?id=1832244
not sure if I got the right component, though.

**Comment by periklis** [comment]
> @periklis done: https://bugzilla.redhat.com/show_bug.cgi?id=1832244
> not sure if I got the right component, though.

All good! Does this blog 4.1 z-stream?

**Comment by thiagoalessio** [comment]
> All good! Does this block 4.1 z-stream?

No, we can always build & publish OLM Operator Metadata later, without blocking the release ... and it might be a while until we have a next 4.1, so no time pressure :sunglasses:

**Comment by periklis** [comment]
Ok thx will set it to medium priority and do it on the next free slot. Please close this issue.

**Comment by jcantrill** [comment]
Closing in favor of bz
