### ISSUE TITLE
Set max_map_count when using minishift

### ISSUE THREAD

**Issue by jpkrohling** [openshift/cluster-logging-operator#53]
Follow-up from #41: when deploying the example and the OpenShift cluster is set via `minishift`, the script should run the following:

```
minishift ssh -- sudo sysctl -w vm.max_map_count=262144
```

**Comment by jcantrill** [comment]
Does this resolve your issue? https://github.com/openshift/elasticsearch-operator/blob/master/hack/deploy-setup.sh#L42  In practice, the cluster-node-tuning-operator will make these changes to the appropriate infra node

**Comment by jcantrill** [comment]
Closing per https://github.com/openshift/cluster-logging-operator/issues/53#issuecomment-450949655
