### ISSUE TITLE
Use existing ES cluster

### ISSUE THREAD

**Issue by mrethers** [openshift/cluster-logging-operator#534]
Hi,

I'm using an Elasticsearch cluster for a search project using the Elastic operator from elastic.co. Now I want to turn on cluster logging but it seems it will try and create another cluster altogether.

Given the heavy resource requirements of ES clusters, how can I leverage my existing one instead of letting this operator to create a new one? I can't seem to find anything in the ClusterLogging CR to do that, at least in the 4.2 version.

Thanks

**Comment by mrethers** [comment]
It just occurred to me that I can just set the cluster in unmanaged state and update the fluentd DS to point to the ES cluster that I already have. I also have to delete the created ES cluster that was created. Same for Kibana.

**Comment by jcantrill** [comment]
> Hi,
> 
> I'm using an Elasticsearch cluster for a search project using the Elastic operator from elastic.co. Now I want to turn on cluster logging but it seems it will try and create another cluster altogether.
> 

Create an instance of ClusterLogging but do not define the "logstore" stanza.  This well keep the CLO from creating an instance of Elasticsearch

Since this is a 4.2 cluster you are correct in your only choice is to go unmanaged and edit the DS.  Starting with 4.3 you can use LogForwarding TechPreview to have the CLO create fluent to ES config for you

**Comment by himmakam** [comment]
Hi, can I know how I can enable LogForwarding to have the logs forwarded to elastic search managed by another openshift cluster. Is this a valid scenario and can be used. I exposed elastic search in the target openshift cluster as a route. Then if I just point to the route, it says connection refused. Might be need some certificates. Are there any instructions/steps to do this.

**Comment by jcantrill** [comment]
This is a LogForwarding feature that is TP starting in 4.4 and shortly goes GA in 4.6
