### ISSUE TITLE
Does CLO managed state control EO managed state?

### ISSUE THREAD

**Issue by jcantrill** [openshift/cluster-logging-operator#61]
Working through config options and the spec: 

* What happens when I set the CLO to Unmanged?
* What happens when I set the EO to Unmanaged but CLO is managed?

We need to sort this out, and describe it in our documention

**Comment by ewolinetz** [comment]
>    What happens when I set the CLO to Unmanged?

Simply, any changes made to the ClusterLogging CR object won't be reflected on the cluster. But if the Elasticsearch object were manually updated the EO would make changes to the cluster (assuming it was still 'Managed')

>    What happens when I set the EO to Unmanaged but CLO is managed?

The CLO would update the Elasticsearch objects it manages, but the EO won't make any changes to the cluster.
