### ISSUE TITLE
PersistentVolumeClaim does not seem like a viable storage choice

### ISSUE THREAD

**Issue by jcantrill** [openshift/cluster-logging-operator#63]
Based on the description in [1] repeated here, this does not seem like a viable choice to represent the ES node storage.  The description would indicate you can only specify a single, existing PVC which is not usable for anything but a single node ES cluster.  
```
 78     // PersistentVolumeClaim will NOT try to regenerate PVC, it will be used
 79     // as-is. You may want to use it instead of VolumeClaimTemplate in case
 80     // you already have bounded PersistentVolumeClaims you want to use, and the names
 81     // of these PersistentVolumeClaims doesn't follow the naming convention.
 82     PersistentVolumeClaim *v1.PersistentVolumeClaimVolumeSource `json:"persistentVolumeClaim,omitempty"`
```
Additionally, we provide no mechanism to specify or default a storage class.  This seems like an issue given I thought storageClass was the convenient way to define storage in a single representation of kind, size, etc.

[1] https://github.com/openshift/elasticsearch-operator/blob/master/pkg/apis/elasticsearch/v1alpha1/types.go#L78-L82

**Comment by jcantrill** [comment]
Revisiting this issue in general, we should consider removing storage configuration from CLO with the exception of maybe `storageclass`.  Again, operating under the principle that we want cluster logging to work OOTB for 98% of deployments targeting AWS clusters, we can make assumptions:
* We will create PVC with a particular storage class
* User's can go `unmanaged` to specify alternates
* We want to drive user's to our notion of correctness in regards to the deployment when adopting clusters
@jwforres Does this fit into our overall direction with the product.

**Comment by jcantrill** [comment]
Dependency resolved by https://github.com/openshift/elasticsearch-operator/pull/55

**Comment by jwforres** [comment]
sorry i missed your last comment while I was out. Should compare with what the registry team (@bparees ) is planning to do for filesystem storage and what's different about the two use cases. For logging it sounds like you have a PVC for each of your ES nodes?

**Comment by jcantrill** [comment]
> sorry i missed your last comment while I was out. Should compare with what the registry team (@bparees ) is planning to do for filesystem storage and what's different about the two use cases. For logging it sounds like you have a PVC for each of your ES nodes?

@jwforres Settled on default class of 'gp2' and 200G based whats used in dedicated and information from the storage team.  This info is required in the CR.  We decided the example and making the request intentional and explicit was better then defaulting if not defined.  Is that decision consistent with the desire of the architecture team?

**Comment by jcantrill** [comment]
CLO will create the CR for elasticsearch to create a single PVC for each Elasticsearch node using the class and size that presumably already exists.

**Comment by bparees** [comment]
> registry will not default the storage on platforms where it uses filesystem storage, it will wait until the admin fills out the storage section of the CR with the PVC to use.

I think our plan was that we'd create a PVC with specific requirements(e.g. RW-many) and expect the cluster to provide a PV that can meet the PVC requirements.  But we haven't implemented this flow yet.

That said, i'm ok with what you've described too :)

**Comment by jwforres** [comment]
@bparees hmm i do like reducing potential screw-ups by forcing the RW-many

**Comment by bparees** [comment]
> @bparees hmm i do like reducing potential screw-ups by forcing the RW-many

nothing would currently stop them from referencing a different PVC (since we don't block changing storage config) so this is primarily about trying to ensure we have an out of box install experience that gives you a running registry.

**Comment by jcantrill** [comment]
Closing as this well be resolved also by https://github.com/openshift/cluster-logging-operator/pull/70
