### ISSUE TITLE
Feature Request: Allow list of ElasticSearch endpoints in Log Forwarding API

### ISSUE THREAD

**Issue by ThomasVitt** [openshift/cluster-logging-operator#630]
Hello,

in Openshift 4.5 I would like to send the logs collected by fluentd to multiple elasticsearch endpoints. My ELK administrator sent me a list of three ES nodes, to which fluentd is supposed to send the logs. There is no loadbalancer in front of ES. 

In the LogForwarding CR you can only specify one FQDN for each endpoint: 

oc describe crd logforwardings.logging.openshift.io
[..]
    Schema:
      openAPIV3Schema:
        Properties:
          Spec:
            Description:  Specification for logforwarding of messages
            Properties:
              Outputs:
                Description:  Destinations for log messages
                Items:
                  Description:  An individual entry for a specific output
                  Properties:
                    Endpoint:
                      Description:  the url to the the service defined by this output
=>                 Type:         string
                    Name:
                      Description:  The name of the output
                      Type:         string
[..]

I would like to specify a list of hosts, and fluentd chooses one of them. 
Fluentd accepts a list of hosts (https://docs.fluentd.org/output/elasticsearch#hosts-optional)

Thanks, Thomas

**Comment by jcantrill** [comment]
@sichvoge do you want to add a proper  feature request for this issue?
> I would like to specify a list of hosts, and fluentd chooses one of them.
> Fluentd accepts a list of hosts (https://docs.fluentd.org/output/elasticsearch#hosts-optional)

@alanconway this would be maybe part of the tuning proposal?

> 
> Thanks, Thomas

@lukas-vlcek Doesn't ES do some sort of load balancing itself between the cluster

**Comment by alanconway** [comment]
If you want to send to multiple endpoints, you can create multiple outputs and a pipeline with multiple outputRefs. The existing API can do that. Am I missing something?

**Comment by ThomasVitt** [comment]
Yes, we want to do client-side loadbalancing, as we have two logstash nodes for distributing the load. 
We do not want to use each logstash as a separate data sink by configuring so in the log forwarding API, this would result in having each log line twice in the elastic stack.

**Comment by alanconway** [comment]
OK, we can handle it the same way we do for Kafka. 

We should review whether we implement multiple connection URLs on a case-by-case basis, or if this might be common enough to deserve a standard pattern that we can apply to any output that needs it.

**Comment by jcantrill** [comment]
Following up here, I believe Elasticsearch does its own loadbalancing depending upon how and index is sharded and the number of shards.  By default CL will shard N times up to 5 ES nodes.  Additionally, fluent is setup to reload its connections every 200 requests.  Finally, it was my understanding the internal service proxy should balance across the endpoints.

**Comment by jcantrill** [comment]
if you believe there is still a feature to be had please open an RFE https://issues.redhat.com/
