### ISSUE TITLE
Create custom elasticsearch index in fluentd configuration

### ISSUE THREAD

**Issue by abu-2020-ghub** [openshift/cluster-logging-operator#634]
Can you details out steps to create custom elasticsearch index in fluentd configuration.

Tried like below, but it says cannot create any new index other than project_full, operations_full..

```
<elasticsearch_index_name>
     enabled "true"
     tag "myapp*"
     name_type custom_index
</elasticsearch_index_name>
```

Thanks for any help in advance

**Comment by jcantrill** [comment]
The change you are trying to make is not what you believe it to be.  Please reference https://github.com/openshift/origin-aggregated-logging/tree/master/fluentd/lib/fluent-plugin-viaq_data_model

**Comment by abu-2020-ghub** [comment]
Thanks for your quick response. I will try to run through this link. Additionally is there any document that explains how to write fluentd configurations for handling user application logs from stdout with filters applied using this operator.

Thanks again in advance !!
