### ISSUE TITLE
Ability for fluentd forward a copy of logs to a kafka endpoint

### ISSUE THREAD

**Issue by abu-2020-ghub** [openshift/cluster-logging-operator#643]
**Feature:** Ability for fluentd forward a copy of logs to a kafka endpoint with cluster logging operator

Is this provision already supported and part of OCP 4.4?

Thanks in advance

**Comment by periklis** [comment]
@abu-2020-ghub No this feature will not be part of OCP 4.4. However, it will be released as part of Logforwarding GA in 4.6 and eventually later as part of 4.5.z.

**Comment by abu-2020-ghub** [comment]
Thanks for your quick reply. Is there any other alternative approach today for the same?

**Comment by periklis** [comment]
@abu-2020-ghub I cannot recommend any approach lacking experience. However forwarding to a fluentd-forward target and then to kafka via fluentd-plugin-kafka could be a bridged approach.

**Comment by abu-2020-ghub** [comment]
@periklis Thanks once again. Will explore the same

**Comment by periklis** [comment]
@abu-2020-ghub Would be delighted if you can report your results back!

**Comment by abu-2020-ghub** [comment]
@periklis Sure, will report the results after our exploration and trial

**Comment by jcantrill** [comment]
This will be available in 4.6 GA only.
