### ISSUE TITLE
Option to forward/send application events/traces to fluentd service endpoint to capture important application events

### ISSUE THREAD

**Issue by abu-2020-ghub** [openshift/cluster-logging-operator#663]
We have been exploring if there is an option to forward/send application events/traces to fluentd service endpoint to capture important application events. This was easily achievable with stable fluentd helm repo with below configurations and then having it captured in separate index for visualization in Kibana

**But we have not been successful with cluster-logging-operator. Any help would be highly appreciated.**
```
  <match **>
          @type copy
          <store>
            @type stdout
          </store>
          <store>  
            @id elasticnfexception
            @type elasticsearch
            @log_level info
            include_tag_key false
           # Replace with the host/port to your Elasticsearch cluster.
            host "#{ENV['OUTPUT_HOST']}"
            port "#{ENV['OUTPUT_PORT']}"
            scheme "#{ENV['OUTPUT_SCHEME']}"
            ssl_version "#{ENV['OUTPUT_SSL_VERSION']}"
            logstash_format true
            logstash_prefix Events-NfException
            type_name _doc
          </store>
```

**Comment by jcantrill** [comment]
> We have been exploring if there is an option to forward/send application events/traces to fluentd service endpoint to capture important application events. This was easily achievable with stable fluentd helm repo with below configurations and then having it captured in separate index for visualization in Kibana
> 
> **But we have not been successful with cluster-logging-operator. Any help would be highly appreciated.**

Please define "success".  What is not working for you.

This is an operator that is designed to drive components to a state as spec'd by the clusterlogging resource.  The collector config is generated based on the clusterlogforwarder resource.  The only way for you to modify the config is to place the CLO into an unmanaged state and take control of the collector config

**Comment by abu-2020-ghub** [comment]
Ok Thank You..What we want to achieve is as explained below:

We have some apps which publish events to fluentd end point in addition to writing std-out logs. We want to capture these events separately in an index for troubleshooting.  std-out logs are by default getting captured.
We point to fluentd service with servicename and port and connection has been successful.

Hence we are looking for a solution about what configurations need to be done on fluentd configmap such that these apps published events can be captured and redirected to any existing or new index.

We have tried few blogs, but have been unsuccessful.

Thanks in advance

**Comment by jcantrill** [comment]
As identified in earlier comments, this stack is highly opinionated and would require you to modify several things to accomplish your goals.  I don't believe this use case fits the overall direction of OpenShift Logging but please feel free to open an RFE https://issues.redhat.com for it to be taken into consideration
