### ISSUE TITLE
What's recommended for structured multiline logging?

### ISSUE THREAD

**Issue by arve0** [openshift/cluster-logging-operator#729]
**Environment:** on prem openshift 4.5
**Operator channel:** 4.4
**Applications:** mix of java, node and go

I've read [Configuring the logging collector](https://docs.openshift.com/container-platform/4.5/logging/config/cluster-logging-collector.html), https://github.com/openshift/origin-aggregated-logging/issues/1492 and https://github.com/openshift/origin-aggregated-logging/issues/28, but not found a recommended setup for structured multiline logging. 

Mainly miss multiline stack-traces in one message. Have found `pipeline_metadata.collector.received_at`, which helps for multiline stack-traces.

As I understand it, [JSON-logging is not supported](https://docs.openshift.com/container-platform/4.5/logging/config/cluster-logging-maintenance-support.html). Are there alternatives?

**Comment by jcantrill** [comment]
> **Environment:** on prem openshift 4.5
> **Operator channel:** 4.4
> **Applications:** mix of java, node and go
> 
> I've read [Configuring the logging collector](https://docs.openshift.com/container-platform/4.5/logging/config/cluster-logging-collector.html), [openshift/origin-aggregated-logging#1492](https://github.com/openshift/origin-aggregated-logging/issues/1492) and [openshift/origin-aggregated-logging#28](https://github.com/openshift/origin-aggregated-logging/issues/28), but not found a recommended setup for structured multiline logging.
> 
The recommendation is you wrapper the log message in JSON but then you get hit by the fact CL no longer parses JSON payloads.  This was done as a defensive mechanism to keep the storage from falling over.   

> Mainly miss multiline stack-traces in one message. Have found `pipeline_metadata.collector.received_at`, which helps for multiline stack-traces.
> 
> As I understand it, [JSON-logging is not supported](https://docs.openshift.com/container-platform/4.5/logging/config/cluster-logging-maintenance-support.html). Are there alternatives?

These issues are being tracked here:

* https://issues.redhat.com/browse/LOG-843
* https://issues.redhat.com/browse/LOG-835

**Comment by arve0** [comment]
I'm unable to view LOG-835 and LOG-843 with my Red Hat account. Any ideas?
