### ISSUE TITLE
Please prepare bundle for OCP 4.7

### ISSUE THREAD

**Issue by Ximinhan** [openshift/cluster-logging-operator#742]
Now that we are fully branched for 4.7, please prepare your operator to supply a 4.7 bundle, so that 4.7 operator publishing works and doesn't overwrite 4.6 bundles. This means at least updating the package.yaml under https://github.com/openshift/cluster-logging-operator/tree/master/manifests
@jcantrill @richm

Reference: https://github.com/openshift/ocp-build-data/pull/708

**Comment by periklis** [comment]
@Ximinhan We already have a PR for that: #736 However, we are heading towards disconnecting openshift-logging from ART and move to CPAAS for our releases >4.6: openshift/ocp-build-data#689

**Comment by Ximinhan** [comment]
oh I got it, thanks.
