### ISSUE TITLE
feature: enable multiline application log parsing with concat via environment variable

### ISSUE THREAD

**Issue by jgrumboe** [openshift/cluster-logging-operator#753]
I experimented with the CONCAT label stanza to do multiline parsing for Spring boot apps.

I changed the original stanza https://github.com/openshift/cluster-logging-operator/blob/b440b7428200cb2e689aaef85ae2abf3c7404faf/pkg/generators/forwarding/fluentd/templates.go#L71
to the following:

```
    <label @CONCAT>
      <filter kubernetes.**>
        @type concat
        key log
        partial_key logtag
        partial_value P
        separator ''
      </filter>
      <filter kubernetes.**>
        @type concat
        key log
        multiline_start_regexp /^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}/
        timeout_label @INGRESS
        flush_interval 3s
      </filter>
      <match kubernetes.**>
        @type relabel
        @label @INGRESS
      </match>
    </label>
```
As you can see I added a second filter stanza with a multiline_start_regexp containing the standard timeformat logline start for Spring Boot Apps.

It would be great if this could be made available via an environment variable which configures the multiline_start_regexp and only if it is set the second filter stanza will be inserted.
So users/admins would be able to configure a custom multiline pattern which suits their apps and needs.

**Comment by jgrumboe** [comment]
@simonkrenger FYI

**Comment by jcantrill** [comment]
All configuration is done through CR and generation not via env. We need to consider how this applies to various applications as one log format does not apply to every service on the cluster

**Comment by jgrumboe** [comment]
You could add a new option e.g. 'Multiline-Logformat' to the CR and this could be used to generate the multiline regex config.
I know it probably wouldn't apply to every service in the cluster but it would be to the clusteradmin to find a good regex to match the majority of his services. It wouldn't be Openshift to find/preconfigure a 'correct' multiline match, you would just enable the admin.

**Comment by jcantrill** [comment]
@jgrumboe closing this issue.  I would encourage you to file an RFE here https://issues.redhat.com/projects/LOG/summary  there likely is another regarding multi-line parsing
