### ISSUE TITLE
[Openshift 4.5][kibana] Automate import of kibana dashboard and visualization

### ISSUE THREAD

**Issue by sreenichelikam** [openshift/cluster-logging-operator#778]
We trying to automate the kibana dashboard and visualization import using curl commands. 

**Describe the bug**
We followed kibana import API from the https://www.elastic.co/guide/en/kibana/current/dashboard-import-api.html by using kibana route and didn't success.

**Environment**
-  OpenShift Version: 4.5, 
- Cluster Logging Operator: 4.5.0-202010221357
- Kibana: 6.8.1

**Additional context**
Can you please help suggest other ways or api  to automate import of kibana dashboard and visualization using curl.

**Comment by jcantrill** [comment]
That link is for 7.x which is unsupported by the elasticsearch operator though it looks like there are similar reference here https://www.elastic.co/guide/en/kibana/6.8/dashboard-import-api.html.  This API is not officially supported and likely requires some tweaks in permissions.  Alternatively, if you have access to the logging namespace you might find the following adhoc script satisfies your needs.  The script is provided as-is without any official support: https://github.com/jcantrill/cluster-logging-tools/blob/master/scripts/import-kibana-objects
