### ISSUE TITLE
fluentd pods scheduled only on worker nodes

### ISSUE THREAD

**Issue by jatanmalde** [openshift/cluster-logging-operator#78]
I deployed the logging-stack refering the `README.md` file and the operators and pods were up and running. 

I could not see `nodeSelector` anymore on the ds configuration, but the fluentd pods are only up and running on worker nodes and not master nodes.
```
[root@localhost ocp1]# oc get pods -owide -l component=fluentd
NAME            READY     STATUS    RESTARTS   AGE       IP            NODE
fluentd-4xxgl   1/1       Running   0          36m       10.131.x.xx   ip-10-0-xxx-xx.us-east-2.compute.internal
fluentd-r56fp   1/1       Running   0          36m       10.128.x.xx   ip-10-0-143-93.us-east-2.compute.internal
fluentd-swrqv   1/1       Running   0          36m       10.129.x.xx   ip-10-0-175-200.us-east-2.compute.internal
[root@localhost ocp1]#
```
The cluster comprises of 6 nodes which includes 3 masters and 3 worker nodes on it.

Could some check if this is expected behavior or am I missing something on it?

**Comment by jcantrill** [comment]
Fixed by https://jira.coreos.com/browse/LOG-318.  Spec missing taints.
