### ISSUE TITLE
How to call k8s api from ConfigGenerator

### ISSUE THREAD

**Issue by k-keiichi-rh** [openshift/cluster-logging-operator#787]
To implement  [Forwarder Label Selector](https://github.com/openshift/enhancements/blob/master/enhancements/cluster-logging/forwarder-label-selector.md), ConfigGenerator needs to access to k8s cluster to forward application logs only from pods identified by labels.

In current implementation, ConfigGenerator instance doesn't have ClusterLoggingRequest instance that can access to k8s cluster  via k8shandler package. And ConfigGenerator class is loosely coupled with ClusterLoggingRequest class.
```
[ From generateCollectorConfig() in ClusterLoggingRequest class ]
        generator, err := forwarding.NewConfigGenerator(
                clusterRequest.Cluster.Spec.Collection.Logs.Type,
                clusterRequest.includeLegacyForwardConfig(),
                clusterRequest.includeLegacySyslogConfig(),
                clusterRequest.useOldRemoteSyslogPlugin(),
        )
        if err != nil {
                log.Error(err, "Unable to create collector config generator")
                return "",
                        clusterRequest.UpdateCondition(
                                logging.CollectorDeadEnd,
                                "Unable to generate collector configuration",
                                "No defined logstore destination",
                                corev1.ConditionTrue,
                        )
        }
        clfSpec := &clusterRequest.ForwarderSpec
        fwSpec := clusterRequest.Cluster.Spec.Forwarder
        generatedConfig, err := generator.Generate(clfSpec, fwSpec)
```

There are several option to get the pod list from ConfigGenerator:

1. Extend ConfigGenerator interface to pass the selected pod names identified by labels
```
//ConfigGenerator is a config generator for a given ClusterLogForwarderSpec
type ConfigGenerator interface {

        //Generate the config
        Generate(clfSpec *logging.ClusterLogForwarderSpec, fwSpec *logging.ForwarderSpec, identifiedPodList *corev1.PodList) (string, error)
}
```

2. Extend CLusterLogForwarderSpec class to pass the selected pod names identified by labels

```
type ClusterLogForwarderSpec struct {
	logging.ClusterLogForwarderSpec
        IdentifedPodList *coreV1.PodList `json:
}
=> The original ClusterLogForwarderSpec in pkg/apis/logging/v1 should not be fixed to keep compatibility.
       @alanconway advised me to create a container struct that includes the original ClusterLogForwarder.
```

I think Option2 is better than Option1 because we lose the compatibility if we change the ConfigGenerator interface. How would you think it?

**Comment by jcantrill** [comment]
I believe the generator depending upon the API server would be the wrong direction and would suggest that allowing the passing of pod names (option 2) would be a better solution.  My concern here is now the operator will require permissions to list pods across every namespace which I don't believe is ideal either.  I would propose a third option which would be to write a new fluentd plugin which can handle this use case. 

I'm not certain where we are adding this change:
* point of collection
This means we need changes at source collection to define file include/exclude and requires pod names

* some point in the processing pipeline
This means we can evaluate based on what already exists in the record and may not need api access

**Comment by k-keiichi-rh** [comment]
Thank you for your comment.

> I believe the generator depending upon the API server would be the wrong direction and would suggest that allowing the passing of pod names (option 2) would be a better solution. 

I agree that the generator should be independent with the API server.

> My concern here is now the operator will require permissions to list pods across every namespace which I don't believe is ideal either. I would propose a third option which would be to write a new fluentd plugin which can handle this use case.
> I'm not certain where we are adding this change:
> 
> * point of collection
>   This means we need changes at source collection to define file include/exclude and requires pod names

There is another issue of how often we should call Reconcile() to update fluent.conf to define the file include/exclude.
@alanconway advised me that 
> we reconcile on a fixed interval (I think 30secs) at each reconcile we check if anything has changed to avoid useless restarts of fluentd. I believe  we should adopt a more event-driven strategy, where we watch resources that affect our configuration and respond dynamically rather than on a fixed schedule. Either way is feasible, but I think this feature will force us to improve our overall reconcile strategy.

If we have thousands of pod to forward, there are too much entries to define the file include/exclude in fluent.conf. 
And it should be too messy. 

> * some point in the processing pipeline
>   This means we can evaluate based on what already exists in the record and may not need api access

I think that Filter plugin of fluentd is the right place to filter unnecessary application log by pod labels.
And I confirmed whether the pod labels are included in fluentd records or not.
They are included. And we won't need to access to k8s api server anymore if we take this way.

So I think that the third option you suggested is the correct option. How would you think?
Please correct me if my understanding wrong.

```
$ oc get pods -n openshift-sdn sdn-xgv88
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-11-11T02:44:43Z"
  generateName: sdn-
  labels:
    app: sdn
    component: network
    controller-revision-hash: 7669646878
    openshift.io/component: network
    pod-template-generation: "1"
    type: infra
```
The following log is sample sdn-xgv88 for confirmation.
I can use "flat_labels" record to identify pods to filter.
```
Oct 15 02:17:31 fluentd-sfwm6 fluentd docker:{
"container_id"=>"767ce2253b3eacf2c28d87065ad3d429012ff1a23f5aae4cf39c264190b9c176"}
#011kubernetes:{
  "container_name"=>"sdn", 
  "namespace_name"=>"openshift-sdn", 
  "pod_name"=>"sdn-xgv88", 
  "container_image"=>"quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:167c14d56714982360fbaa72b3eb3f8d4fb6c5ad10bbbb7ea396606d8412b7eb", 
  "container_image_id"=>"quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:167c14d56714982360fbaa72b3eb3f8d4fb6c5ad10bbbb7ea396606d8412b7eb", 
  "pod_id"=>"2e8ed24a-f278-4d60-a417-7c710ddf92b0", 
  "host"=>"host-192-168-69-55", 
  "master_url"=>"https://kubernetes.default.svc", 
  "namespace_id"=>"12a80b10-fa08-11e9-94c7-fa163e7fd80f", 
  "namespace_labels"=>
    {
      "name"=>"openshift-sdn", 
      "openshift_io/cluster-monitoring"=>"true",   
      "openshift_io/run-level"=>"0"
    }, 
  :flat_labels=>["app=sdn", "component=network", "controller-revision-hash=7669646878", "pod-template-generation=14", "type=infra", "openshift_io/component=network"]
}
#011message:I1013 07:12:38.276282    2178 pod.go:541] CNI_DEL mtest/brdsamplepod1-7874cd5dbd-mxjv2#011level:unknown#011hostname:host-192-168-69-55
#011pipeline_metadata:{
  "collector"=>
    {
      "ipaddr4"=>"192.168.69.55", 
      "inputname"=>"fluent-plugin-systemd", 
      "name"=>"fluentd", 
      "received_at"=>"2020-10-15T02:15:53.040097+00:00", 
      "version"=>"1.7.4 1.6.0"
     }
}
#011@timestamp:2020-10-13T07:12:38.276433+00:00
#011viaq_index_name:infra-write#011viaq_msg_id:MmNmODZkYmUtMWUzMC00NGRkLThhNTQtMmI2YjE2OTY3Zjc2
```

**Comment by jcantrill** [comment]
I encourage you to review the pipeline as we explicitly configure a plug-in to add pod labels and there is another filter that flattens them. It's worth having a larger design discussion about a filter to do the tasks you describe

**Comment by k-keiichi-rh** [comment]
Thank you for pointing me. I will review it and propose the design to discuss.
