### ISSUE TITLE
[Question] - How to add authorization to Logging Operator's Kibana?

### ISSUE THREAD

**Issue by dperezro** [openshift/cluster-logging-operator#816]
Hello! I have looked for a way to add authorization to the operator's Kibana (or elasticsearch) and have found nothing. Can you please advise if whether it's supported or not in openshift? So far we have wide AAD (OpenID) authentication to Openshift and that also serves to access Kibana but once there, all users seems to have the same rights and I've not found a way to add security there. Thank you!

**Comment by jcantrill** [comment]
Authorization is granted based upon Openshift existing permissions. Users have the ability to see logs associated with their project visibility. Admins can see all longs as well as infrastructure logs

**Comment by dperezro** [comment]
@jcantrill thank you very much for the explanation. Now it's very clear. I'll close this one. Thanks again!
