### ISSUE TITLE
Add the possibility to customize the indice names when forwarding logs to elasticsearch

### ISSUE THREAD

**Issue by titou10titou10** [openshift/cluster-logging-operator#818]
**This is a feature request**

Currently it seems that when forwarding the logs to an external elasticsearch instance, the name of the indicees are hard-coded: app-write, audit-write etc and there is no way to customize those names       
As an OCP cluster admin, I want to customize the names of the indices used by the ClusterLogForwarder when forwading logs to elasticsearch

**Environment**
- OCP v4.6.4
- Cluster Logging  operator v4.6.0-202011041933.p0
- external elasticsearch v7.10
- setup done as described in the "Forwarding logs to an external Elasticsearch instance" official doc

As we are forwarding logs from multiple OCP clusters to a single elasticsearch cluster, we want to assign a specific per cluster name to the indice in elasticsearch, and not have all of our clusters use the same indice

Ref: https://docs.openshift.com/container-platform/4.6/logging/cluster-logging-external.html#cluster-logging-collector-log-forward-es_cluster-logging-external

**Comment by jcantrill** [comment]
@sichvoge do we have a JIRA for this?

**Comment by jcantrill** [comment]
> **This is a feature request**
> 
> Currently it seems that when forwarding the logs to an external elasticsearch instance, the name of the indicees are hard-coded: app-write, audit-write etc and there is no way to customize those names

As manager of the external instance I would recommend aliasing the indices as needed.  The internally managed store relies on rollover and uses the pattern recommended by ES which is to point the alias to a differently named alias (e.g. `app-write` -> `app-00001`)

**Comment by titou10titou10** [comment]
> 
> 
> As manager of the external instance I would recommend aliasing the indices as needed. The internally managed store relies on rollover and uses the pattern recommended by ES which is to point the alias to a differently named alias (e.g. `app-write` -> `app-00001`)
This does not fullfil the requirement, ie having 4 OCP clusters forwarding applications logs to different indiexes to a single elasticsearch instance. Except if it is possible to specify an alias on the "cluster logging operator" side, which is the subject of this FR

**Comment by jcantrill** [comment]
Please open a formal RFE request here https://issues.redhat.com/projects/LOG/summary
