### ISSUE TITLE
Feature request - Add keepalive option for fluent forward config

### ISSUE THREAD

**Issue by cpmoore** [openshift/cluster-logging-operator#829]
Currently there is no way to set the keepalive in the fluent forward config when forwarding logs to external fluentd.
By default keepalive is set to false, which means a new socket is created for every chunk sent.  I feel that this is inefficient and would prefer to use the existing socket connection to send logs.

We have tested this using the legacy method of using the config map to configure forwarding and it works the way we expect it to.

**Comment by jcantrill** [comment]
@sichvoge @alanconway  we his may be something we could just flip to true or add it to the tuning bits

**Comment by alanconway** [comment]
I think flip to true, I can't imagine a use case where it's better to use a separate connection for each chunk set. In particular with TLS, the connection setup overhead is large.

**Comment by cpmoore** [comment]
@alanconway 
I would agree with that.  Especially since with the keepalive set to false, fluentd doesn't seem to close the open sockets, even if they're not being used anymore.  They only get closed when the eventual network tcp timeout is reached.

**Comment by alanconway** [comment]
> @alanconway
> I would agree with that. Especially since with the keepalive set to false, fluentd doesn't seem to close the open sockets, even if they're not being used anymore. They only get closed when the eventual network tcp timeout is reached.

Grrr, I hate clients that do that (ever since I stopped writing them myself, ahem :)

**Comment by sichvoge** [comment]
Added a new Feature Request for this item on our Jira project as well so we can track it. https://issues.redhat.com/browse/LOG-1186
