### ISSUE TITLE
unable to install instances from the UI on 4.6.8

### ISSUE THREAD

**Issue by ryandawsonuk** [openshift/cluster-logging-operator#843]
**Describe the bug**
Trying to install on openshift 4.6.8 following [the docs](https://docs.openshift.com/container-platform/4.6/logging/cluster-logging-deploying.html). Just using the docs. Can't create an instance.

**Environment**
- openshift 4.6.8
- ClusterLogging 4.6.0-202011221454.p0

**Logs**
The ClusterServiceVersion is installed correctly:
```
kubectl get clusterserviceversions.operators.coreos.com -n openshift-logging clusterlogging.4.6.0-202011221454.p0
NAME                                   DISPLAY           VERSION                 REPLACES   PHASE
clusterlogging.4.6.0-202011221454.p0   Cluster Logging   4.6.0-202011221454.p0              Succeeded
```

The install status is successful:
![image](https://user-images.githubusercontent.com/22754674/102502578-b44a0300-4076-11eb-90b2-c60100e7b3b9.png)

There is a running pod called `cluster-logging-operator-5d7cd4d698-p5lx7` in the `openshift-logging` namespace and there are no errors in its logs.

But if I go to the `Cluster Logging` tab I get:
![image](https://user-images.githubusercontent.com/22754674/102502854-0559f700-4077-11eb-9d48-bee06c9c5f1b.png)

This is not correct as I do have the CRD installed:
![image](https://user-images.githubusercontent.com/22754674/102502997-2d495a80-4077-11eb-807b-3ea0f0cc2775.png)

```
kubectl get crd clusterloggings.logging.openshift.io 
NAME                                   CREATED AT
clusterloggings.logging.openshift.io   2020-12-17T14:28:22Z
```
A snippet from the CRD:
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2020-12-17T14:28:22Z"
  generation: 1
  labels:
    operators.coreos.com/cluster-logging.openshift-logging: ""
... <omitted for brevity> ...
  name: clusterloggings.logging.openshift.io
  resourceVersion: "1285451"
  selfLink: /apis/apiextensions.k8s.io/v1/customresourcedefinitions/clusterloggings.logging.openshift.io
  uid: 835580b8-f0b6-4b53-bb81-7b7abe18fa7c
spec:
  conversion:
    strategy: None
  group: logging.openshift.io
  names:
    categories:
    - logging
    kind: ClusterLogging
    listKind: ClusterLoggingList
    plural: clusterloggings
    shortNames:
    - cl
    singular: clusterlogging
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.managementState
      name: Management State
      type: string
    name: v1
```

**Expected behavior**
I should be able to create a ClusterLogging instance from the openshift UI.

**Actual behavior**
I get the 404 error. 'The server doesn't have a resource type ClusterLogging.'

I can actually create ClusterLogging instances from the command-line.

For other operator CRDs I can get see instances (e.g. knative-eventing).

**To Reproduce**

Follow https://docs.openshift.com/container-platform/4.6/logging/cluster-logging-deploying.html on a new openshift 4.6.8 aws cluster

**Additional context**
I have a few cluster-wide operators installed.

![image](https://user-images.githubusercontent.com/22754674/102504564-e9575500-4078-11eb-8704-715a19eb1697.png)

**Comment by jcantrill** [comment]
I have seen this before and is an issue with OLM, not Cluster logging.  You simply need to either wait or refresh the screen:

![image](https://user-images.githubusercontent.com/4548408/102521041-6b884f00-4062-11eb-9a9b-b799fc4f50d4.png)
