### ISSUE TITLE
Ability to install only the fluentd component

### ISSUE THREAD

**Issue by reggie-k** [openshift/cluster-logging-operator#854]
I want to use the fluentd to forward audit logs to a third party system.
Currently (OCP 4.6), I am forced to install EO (which will also install kibana), which I will not be using.

I think that enabling the install of fluentd solely is a must.

What workaround can I use in the meantime? I really don't wanna install EO (running in a disconnected environment, bringing images to which is extremely painful, even with the disconnected env operator hub procedure, so trying to stick only to the images required).

**Comment by jcantrill** [comment]
> I want to use the fluentd to forward audit logs to a third party system.
> Currently (OCP 4.6), I am forced to install EO (which will also install kibana), which I will not be using.

Resolved by https://github.com/openshift/cluster-logging-operator/pull/814 

> 
> I think that enabling the install of fluentd solely is a must.

If you only require a collector then only define the collector section in ClusterLogging instance. This keeps the operator from deploying storage and visualization

> 
> What workaround can I use in the meantime? I really don't wanna install EO (running in a disconnected environment, bringing images to which is extremely painful, even with the disconnected env operator hub procedure, so trying to stick only to the images required).

Until the referenced PR lands there is no work around; you will still be required to install the EO but you shouldn't need to push any of the other component images except the EO image
