### ISSUE TITLE
How to build cluster-logging-operator from cloned source code

### ISSUE THREAD

**Issue by SAbdulRahuman** [openshift/cluster-logging-operator#881]
Hi ,
  For learning purpose, i cloned cluster-logging operator and trying to build and deploy on Openshift cluster. Getting below error while trying to the operator.
```
$ make deploy
patching file Dockerfile.local (read from Dockerfile)
STEP 1: FROM registry.svc.ci.openshift.org/ocp/builder:rhel-8-golang-1.15-openshift-4.7 AS builder
Error: error creating build container: Error initializing source docker://registry.svc.ci.openshift.org/ocp/builder:rhel-8-golang-1.15-openshift-4.7: Error reading manifest rhel-8-golang-1.15-openshift-4.7 in registry.svc.ci.openshift.org/ocp/builder: unauthorized: authentication required
make: *** [Makefile:98: image] Error 125
```

**Describe the bug**
Trying to build cloned cluster-logging-operator from source, but getting `unauthorized: authentication required` error.

**Environment**
Openshift version 4.6.8
Cloned source to my ubuntu development vm,
- ClusterLogging instance

**Logs**

**Expected behavior**
Need to build & deploy cluster-logging-operator from source to openshift cluster.

**Actual behavior**

**To Reproduce**
1. git clone https://github.com/openshift/cluster-logging-operator.git
2. go get -d -u github.com/openshift/elasticsearch-operator/... github.com/openshift/origin-aggregated-logging/... 
3.  make deploy

**Additional context**

**Comment by jcantrill** [comment]
This requires access to RedHat CI registry.  We have work to do to make it easier for outside users to build and contribute to this project
