### ISSUE TITLE
Init container for fluentd failing due to certificate verify failure

### ISSUE THREAD

**Issue by timvandevoort** [openshift/cluster-logging-operator#898]
**Describe the bug**
Fluentd pods on OKD cluster are failing. After restarting the fluentd pods, they stay in "Init:CrashLoopBackOff" state. The ones in Running state, stay running until they get restarted.

**Environment**
OKD version 4.5.0-0.okd-2020-09-18-202631

**Logs**
Logs from fluentd-init:
/opt/rh/rh-ruby25/root/usr/share/ruby/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate) (OpenSSL::SSL::SSLError)
	from /opt/rh/rh-ruby25/root/usr/share/ruby/net/protocol.rb:44:in `ssl_socket_connect'
	from /opt/rh/rh-ruby25/root/usr/share/ruby/net/http.rb:985:in `connect'
	from /opt/rh/rh-ruby25/root/usr/share/ruby/net/http.rb:920:in `do_start'
	from /opt/rh/rh-ruby25/root/usr/share/ruby/net/http.rb:909:in `start'
	from /opt/rh/rh-ruby25/root/usr/share/ruby/net/http.rb:609:in `start'
	from wait_for_es_version.rb:26:in `<main>'

**Expected behavior**
All fluentd pods should be in Running state.

**Actual behavior**
After restarting the fluentd pods, they stay in "Init:CrashLoopBackOff" state. The ones in Running state, stay running until they get restarted.

**To Reproduce**
Unknown 

**Additional context**
Starting from Red Hat Bugzilla – Bug 1885674 (https://bugzilla.redhat.com/show_bug.cgi?id=1885674) we tried to solve it this way, but without success:

Verified on clusterlogging.4.7.0-202011071430.p0.
1. Set clusterlogging/instance to Unmanaged.
2. Set fluentd.key to blank
   oc edit secret fluentd -n logging ->data.tls.keys: ""
3. Delete one fluentd pod.  The new pod will be in error or Init:CrashLoopBackOff. The /etc/fluent/keys/tls.key in fluentd pods is blank.
   Note: The other fluentd pods are in Running status, although the /etc/fluent/keys/tls.key is blank. The reason is the fluentds are using old secrets until the process was restarted to load the new one.

4. Set clusterlogging/instance back to Managed. and wait for a while
5. Check the fluentd pods status.
   All fluentd pods are running.

Bugzilla 1885674 refers to Bugzilla 1888958 which describes the above steps.

**Comment by timvandevoort** [comment]
This issue was solved after fixing an invalid config of the cluster logging operator.

**Comment by adrianchifor** [comment]
Hey @timvandevoort, what was the invalid config on the operator?
