### ISSUE TITLE
Feature Request: HTTP Output for ClusterLogForwarder 

### ISSUE THREAD

**Issue by yorondevops** [openshift/cluster-logging-operator#925]
Hi, 
Would it be possible to add an HTTP output for sending logs to a custom HTTP endpoint?
Functionally like the existing Elasticsearch Output (meaning it should be able to `POST` logs as JSON), but without all the elasticsearch-specific "stuff".

Must have configuration values:
- The HTTP Method to use (`POST`, `PUT`, etc.)
- A list of custom headers to be added to each request (`Content-Type`, etc.)

**Comment by jcantrill** [comment]
@sichvoge

**Comment by sichvoge** [comment]
I think that makes sense and we do indeed have already a Jira ticket [here](https://issues.redhat.com/browse/LOG-902). I think you should be able to comment on their as well and if so, can you add a little bit more context to for what systems you would use HTTP for. We just want to understand what is out there that can leverage this :) 

Adding your comment from here to this ticket as well. 

So thanks for raising this.

**Comment by sichvoge** [comment]
@jcantrill you can close this issue in favour for our existing Jira ticket.
