### ISSUE TITLE
Feature Request: Delete .kibana indices on failed migration

### ISSUE THREAD

**Issue by tumido** [openshift/cluster-logging-operator#929]
Hi all,

we're repeatedly facing the Kibana being stuck in yellow state because of:

```
plugin:opendistro_security@6.8.1        Setting up index template. 
```

The [only advised solution to this problem](https://access.redhat.com/solutions/5332221) is to delete the failing `.kibana` indices and rollout new kibana deployment. And basically keep doing it until all the problematic indicies are deleted and the migration is successful. In other words: Delete, deploy, check if green, rinse and repeat.

Can this be coded into the operator as an automated problem resolution, please?

Additional context:
https://github.com/operate-first/SRE/issues/98, https://github.com/operate-first/support/issues/83, https://access.redhat.com/solutions/5332221

**Comment by jcantrill** [comment]
this is an operation that would be undertaken by the elasticsearch-operator.  I defer to @ewolinetz if this behavior is already implemented.  Closing.
