### ISSUE TITLE
Include clusterversion and machineconfigpool in the logging's must-gather

### ISSUE THREAD

**Issue by oarribas** [openshift/cluster-logging-operator#935]
Include the `clusterversion` and the `machineconfigpool`, adding the following to the must-gather script, as they have useful information about the state of the cluster if no "default" must-gather executed:
~~~
resources+=(clusterversion)
resources+=(machineconfigpool)

- resources+=(clusteroperators) - # Not this one
~~~

https://github.com/openshift/cluster-logging-operator/blob/master/must-gather/collection-scripts/gather#L14

**Comment by periklis** [comment]
The cluster-logging must-gather is intended to be an extra dump you might want to take in addition to the default must-gather. That's why it is minimalistic. I disagree adding those two here as if they blow up the tarball in the end. If these two resources are minimal, please elaborate how they add value to debugging the OpenShift Logging stack.

**Comment by oarribas** [comment]
Hi @periklis ,

- `clusterversion` only adds one yaml, and it's useful to check the version of the OCP cluster, and also if there is an upgrade in place or if there are any other issues with the cluster operators.
- `clusteroperators` includes lots of things, so probably it's better to no include.

Also, as `nodes` are already included, I think that `machineconfigpool` could be also interesting. It only adds one yaml per mcp, and it will show if any node is updating (even if all are Ready).

On the other hand, if it's expected to collect the logging must-gather in addition to the default must-gather, it would be better to change the command to collect both in the readme to:
~~~
oc adm must-gather --image-stream=openshift/must-gather --image=quay.io/openshift/origin-cluster-logging-operator -- /usr/bin/gather
~~~
** not sure if the `-- /usr/bin/gather` is required for the logging must-gather, as it's the default for the default must-gather

https://github.com/openshift/cluster-logging-operator/blob/master/must-gather/README.md#usage

**Comment by periklis** [comment]
@oarribas TIL that you can declare multiple `must-gather` images per command. This is an excellent change to contribute to the projects. Would you like to add this to the `README.md` in addition to the present command? I would suggest to add them both and let our users decide which one to pick.
