### ISSUE TITLE
Question - Is it possible to target specific resource (pod/namespace) for its logs only?

### ISSUE THREAD

**Issue by barvhaim** [openshift/cluster-logging-operator#970]
I am trying to narrow down the logging for a specific pod/namespace, I did not find any info in the documentation, is it supported?

**Comment by periklis** [comment]
@barvhaim Are you speaking of "targeting specific resource pod/namespace" in Kibana? If yes, that's possible via Kibana's query language, e.g.:
```
+kubernetes.namespace_name:YOUR_NAMESPACE +kubernetes.pod_name:YOUR_POD_NAME
```

**Comment by barvhaim** [comment]
@periklis negative, I don't want to collect logs from all of the namespaces/pods available in the app level, I just want to collect logs of specific namespace/pod/deployment, I wonder if there's a way to mark what resources to collect logs from

**Comment by periklis** [comment]
IC now things get clear. I suggest you consult the following section on the docs:
https://docs.openshift.com/container-platform/4.7/logging/cluster-logging-external.html#cluster-logging-collector-log-forward-project_cluster-logging-external
